name: Pull Curriculo on Hostinger
on: 
  push:
    branches: [curriculo]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd public_html
            git pull
