name: Deploy Hostinger

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Push to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd domains/murilot.com/public_html/
          rm -r *
          git clone https://github.com/murilogteixeira/MuriloWebsite.git
          cp -r MuriloWebsite/Output/* .
          rm -r MuriloWebsite
