name: Deploy Hostinger

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SOURCE: "Output/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_PORT: ${{ secrets.PORT }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET }}
