name: Hostinger

on:
  push:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          pwd
          ls -a
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT}}
        user: ${{ secrets.USERNAME}}
        key: ${{ secrets.KEY}}
